### ISSUE TITLE
Add qpmad

### ISSUE THREAD

**Issue by nim65s** [qpsolvers/qpbenchmark#92]
Hi @stephane-caron !

Did you consider adding https://github.com/asherikov/qpmad ?
Some benchmarks are already available at https://github.com/asherikov/qpmad_benchmark, but I guess this repo  provide a better view :)

**Comment by stephane-caron** [comment]
Thanks for pointing it out :+1: This solver was also suggested in https://github.com/qpsolvers/qpsolvers/issues/29 but as far as I know it does not have Python bindings.

If it gets bindings in the future it will be straightforward to add it to [qpsolvers](https://github.com/qpsolvers/qpsolvers) and then configure it in the benchmark. @asherikov FYI (not suggesting you should do the bindings, just so you know your solver is popular demand :smiley:)

**Comment by asherikov** [comment]
Noted, but I am not going to work on this in foreseeable future.

**Comment by stephane-caron** [comment]
Thank you for your feedback. I'll be closing this issue for now.
